# Generated by Django 4.1.3 on 2023-06-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
