# Generated by Django 4.1.3 on 2023-06-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_name_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='vertical',
            field=models.CharField(default='none', max_length=50, unique=True),
        ),
    ]
